/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/overview',
        'getting-started/quick-start',
        'getting-started/faq',
      ],
    },
    {
      type: 'category',
      label: 'Users',
      items: [
        'users/user-guide',
        'users/community',
      ],
    },
    {
      type: 'category',
      label: 'Developers',
      items: [
        'developers/developer-guide',
        'developers/api-reference',
        'developers/api-endpoints',
      ],
    },
    {
      type: 'category',
      label: 'Validators',
      items: [
        'validators/operator-guide',
        'validators/monitoring',
        'validators/key-management',
        'validators/release-guide',
        'validators/release-quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/deployment-guide',
        'operations/MAINNET_DEPLOYMENT_GUIDE',
        'operations/DEVNET_DEPLOYMENT_GUIDE',
        'operations/DEVNET_QUICK_START',
        'operations/DEPLOY_TESTNETS',
        'operations/bridge-checklist',
        'operations/bridge-implementation',
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      items: [
        { type: 'autogenerated', dirName: 'governance' },
      ],
    },
    {
      type: 'category',
      label: 'Specifications',
      items: [
        { type: 'autogenerated', dirName: 'specifications' },
      ],
    },
  ],
};

module.exports = sidebars;
